### PR TITLE
Adding Go Guest for testing.

### PR DESCRIPTION
**Pull request by madflojo**
Recently I've been working with this project and ran into similar issues to the person that opened #4. After seeing the comments I was able to get a working Go Guest and figured it wouldn't hurt to add a Go example in the `testdata/` directory.

For new users, they can use it as an example of how to get it working in their own implementations, and it should help ensure Go support with any upcoming refactoring as well.

### CODE REVIEW

**Comment by madflojo** [comment]
Hey gang, this one has been open for a while so thought I'd just give it a bump. Feel free to shoot any feedback my way.

**Comment by pkedy** [comment]
Thanks for this, @madflojo. I'm working on a solution to #4 and will review this soon. At a glance, it looks very straight forward!

**Comment by madflojo** [comment]
@pkedy was thinking it might be useful to setup the tests to run through multiple languages such as Go, Rust, AssemblyScript, etc. Would that be something you’d be keen on?

**Comment by pkedy** [comment]
@madflojo Absolutely and I'm totally open to ideas. The purpose of the [wapc/language-tests](https://github.com/wapc/language-tests) repo was to do that as well as test the MessagePack and code generator all working together. It's definitely out of date at this point. There needs to be some automation around keeping everything current.

**Comment by madflojo** [comment]
@pkedy ok cool, I have something I was thinking of for this repo but I'll also take a look at the language-tests repo and see if it springs up any thoughts around improving testing.

One thing I'm seeing from some of the other comments is people new to WASM taking a look at this and trying to figure out just how easy or well does it all work together. So the more we can show this repo works across versions/languages the better.

**Comment by madflojo** [comment]
This one is kinda out dated now.

**Pull request closed without merging**
